In [1]:
import pandas as pd
import numpy as np

In [2]:
pd.__version__

'3.0.6'

In [3]:
df = pd.read_csv("https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/car_fuel_efficiency_2026.csv")

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   model_year           10000 non-null  int64  
 1   origin               10000 non-null  str    
 2   fuel_type            10000 non-null  str    
 3   drivetrain           10000 non-null  str    
 4   num_doors            10000 non-null  int64  
 5   engine_displacement  10000 non-null  int64  
 6   num_cylinders        10000 non-null  int64  
 7   horsepower           9123 non-null   float64
 8   vehicle_weight       10000 non-null  int64  
 9   acceleration         9736 non-null   float64
 10  fuel_efficiency_mpg  10000 non-null  float64
dtypes: float64(3), int64(5), str(3)
memory usage: 859.5 KB


In [5]:
df.head(5)

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0


In [6]:
df["fuel_type"].nunique()

3

In [7]:
# column with missing values
df.isna().any().sum()

np.int64(2)

In [8]:
df["fuel_efficiency_mpg"].max()

np.float64(41.2)

In [9]:
horsepower_median = df["horsepower"].median()

In [10]:
horsepower_mode = df["horsepower"].mode()[0]
print(horsepower_mode)

252.0


In [11]:
df["horsepower"] = df["horsepower"].fillna(value=horsepower_mode)

In [12]:
horsepower_na_filled_median = df["horsepower"].median()

In [14]:
print("Before na was remove median: " + str(horsepower_median))
print("After na was removed median: " + str(horsepower_na_filled_median))

Before na was remove median: 254.0
After na was removed median: 252.0


In [15]:
# Confirm if the number of n/a column has reduced after filling horsepower n/a with the observed mode
df.isna().any().sum()

np.int64(1)

In [16]:
# Asian cars
df_asian_cars = df[df["origin"] == "Asia"]

In [17]:
df_asian_cars = df_asian_cars[["vehicle_weight", "model_year"]]
# select first serven records
X = df_asian_cars[:7].to_numpy()

In [18]:
X

array([[4240, 1996],
       [4310, 1992],
       [4230, 1997],
       [4420, 1978],
       [3950, 2007],
       [4750, 2021],
       [4450, 2019]])

In [19]:
XT = X.transpose()

In [20]:
XT

array([[4240, 4310, 4230, 4420, 3950, 4750, 4450],
       [1996, 1992, 1997, 1978, 2007, 2021, 2019]])

In [21]:
XTX = np.matmul(XT, X)
XTX

array([[131950500,  60750580],
       [ 60750580,  28041424]])

In [22]:
# Inverse XTX. using pseudo inverse as normal inverse throws error being a non singular matrix
XTX_inv = np.linalg.pinv(XTX)

In [25]:
print("X:", X.shape)
print("XT:", XT.shape)
print("XTX:", XTX.shape)
print("XTX_inv:", XTX_inv.shape)

X: (7, 2)
XT: (2, 7)
XTX: (2, 2)
XTX_inv: (2, 2)


In [23]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])

In [24]:
# @ is like a short form of np.matmul
w = np.matmul(XTX_inv, XT) @ y

In [26]:
round(w.sum(), 4)

np.float64(0.3692)